### PR TITLE
⁣

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by gir489returns — CHANGES_REQUESTED** [review]
This is unacceptable in its current state. You are changing too many lines. Redo this.

**Comment by PalastP** [comment]
Just use what you find useful, I've made too many changes.

**Comment by gir489returns** [comment]
> Just use what you find useful, I've made too many changes.

I can't tell what you changed because you changed the entire file. Do it over and only submit the most important/useful changes. Like I saw you submit MPPLY_HEISTFLOWORDERPROGRESS changing it to 268435455. Why? Is there a reason to not set the upper 4 bits? Same thing with MPPLY_TIMES_RACE_BEST_LAP, that's a very important change.

Changing price -> Price in a comment? Not important.

**Comment by PalastP** [comment]
> I can't tell what you changed because you changed the entire file. Do it over and only submit the most important/useful changes. Like I saw you submit MPPLY_HEISTFLOWORDERPROGRESS changing it to 268435455. Why? Is there a reason to not set the upper 4 bits? Same thing with MPPLY_TIMES_RACE_BEST_LAP, that's a very important change.
> 
> Changing price -> Price in a comment? Not important.

268435455 is the correct value from the game. All changes should be marked: [https://github.com/YimMenu-Lua/UnlockEverything/pull/11/commits/14a772cb9c86391900a5db829791d0c0122d4d27](url)

**Comment by gir489returns** [comment]
> > I can't tell what you changed because you changed the entire file. Do it over and only submit the most important/useful changes. Like I saw you submit MPPLY_HEISTFLOWORDERPROGRESS changing it to 268435455. Why? Is there a reason to not set the upper 4 bits? Same thing with MPPLY_TIMES_RACE_BEST_LAP, that's a very important change.
> > Changing price -> Price in a comment? Not important.
> 
> 268435455 is the correct value from the game. All changes should be marked: [14a772c](https://github.com/YimMenu-Lua/UnlockEverything/commit/14a772cb9c86391900a5db829791d0c0122d4d27)

You cannot fucking seriously expect me to go through 550 lines of code.

**Comment by PalastP** [comment]
> You cannot fucking seriously expect me to go through 550 lines of code.

When I have time, I will submit it again. No big deal.

**Pull request closed without merging**
